// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwRrvDjLqTMjjrbgwjS5FIhY49XcgHqw',
    appId: '1:44433449173:web:6c79d95bc834343afb425c',
    messagingSenderId: '44433449173',
    projectId: 'roadeye-284ac',
    authDomain: 'roadeye-284ac.firebaseapp.com',
    databaseURL:
        'https://roadeye-284ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadeye-284ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtq4rbmrGPXuObQ-yGSixOfROljO-eYEs',
    appId: '1:44433449173:android:cabd17915a85f8c4fb425c',
    messagingSenderId: '44433449173',
    projectId: 'roadeye-284ac',
    databaseURL:
        'https://roadeye-284ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadeye-284ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4K6N3yOn9fGE8Izfnl2j1-PI38OU8h8',
    appId: '1:44433449173:ios:2a11e338c352157bfb425c',
    messagingSenderId: '44433449173',
    projectId: 'roadeye-284ac',
    databaseURL:
        'https://roadeye-284ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadeye-284ac.firebasestorage.app',
    iosBundleId: 'com.example.appspertanian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4K6N3yOn9fGE8Izfnl2j1-PI38OU8h8',
    appId: '1:44433449173:ios:2a11e338c352157bfb425c',
    messagingSenderId: '44433449173',
    projectId: 'roadeye-284ac',
    databaseURL:
        'https://roadeye-284ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadeye-284ac.firebasestorage.app',
    iosBundleId: 'com.example.appspertanian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwRrvDjLqTMjjrbgwjS5FIhY49XcgHqw',
    appId: '1:44433449173:web:1f31c697c428e9e2fb425c',
    messagingSenderId: '44433449173',
    projectId: 'roadeye-284ac',
    authDomain: 'roadeye-284ac.firebaseapp.com',
    databaseURL:
        'https://roadeye-284ac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'roadeye-284ac.firebasestorage.app',
  );
}
